version: "3.1"

services:
  sam-api:
    build:
      dockerfile: src/Dockerfile
    command: gunicorn --bind 0.0.0.0:5002 wsgi:app
    ports:
      - "8086:5002"
    container_name: my-sam
    networks:
      - default

networks:
  default:
    external:
      name:
        sam_network
